name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install tools
        run: npm install postcss postcss-cli cssnano terser

      - name: Create output directory
        run: mkdir dist

      - name: Copy HTML files
        run: |
          find . -name "*.html" -exec cp --parents {} dist/ \;

      - name: Minify CSS files
        run: |
          find . -name "*.css" -exec bash -c 'postcss "$0" -o "dist/$0"' {} \;
  
      - name: Minify JS files
        run: |
          find . -name "*.js" -exec bash -c 'terser "$0" -o "dist/$0" --compress --mangle' {} \;
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
